#
# Makefile
#
# Makefile for avioos server 
#

include $(POCO_BASE)/build/rules/global

objects = Avioos

target         = avioos
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
